# Generated by Django 2.2.13 on 2021-01-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetupload', '0002_auto_20210127_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_id',
            field=models.IntegerField(),
        ),
    ]
